version: "3.8"
services:
    app:
        container_name: MVC-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"  # HTTP
            - "443:443" # SSL
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
            - phpmyadmin
        environment:
            - APACHE_SSL_CERT_FILE=/etc/apache2/ssl/junicalmedical.com.co.pem
            - APACHE_SSL_KEY_FILE=/etc/apache2/ssl/junicalmedical.com.co.pem  # Reemplaza con la ubicación de tu archivo de clave SSL
        networks:
            - lion
    db:
        image: mysql
        container_name: MVC-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "sistema_medico"
            MYSQL_PASSWORD: "lion"
            MYSQL_ROOT_PASSWORD: "lion"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: MVC-phpmyadmin
        restart: unless-stopped
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "lion"
            MYSQL_ROOT_PASSWORD: "lion"
        networks:
            - lion
volumes:
    mysql_data:
networks:
    lion:
        driver: bridge
