services:
    app:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"  # HTTP
            - "443:443" # SSL
        volumes:
            - ./src:/var/www/html
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
            - phpmyadmin
        networks:
            - lion
    db:
        image: mysql
        container_name: MVC-mysql
        command: --default-authentication-plugin=caching_sha2_password
        restart: unless-stopped
        environment:
            MYSQL_USER: mysql
            MYSQL_DATABASE: database
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - ./conf/mysql/conf/my.cnf:/etc/my.cnf
            - ./mysql:/var/lib/mysql:delegated
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - lion
volumes:
    mysql_data:
networks:
    lion:
        driver: bridge