version: "3"

services:
  my-app:
    container_name: MVC-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: my-app
    user: root
    environment:
      - "APACHE_LOG_DIR:/app"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./.docker/apache:/etc/apache2/sites-available/ssl
      - .:/app
    depends_on:
      - db
      - phpmyadmin
    networks:
      - lion
  db:
        image: mysql
        user: root
        container_name: MVC-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "sistema_medico"
            MYSQL_PASSWORD: "lion"
            MYSQL_ROOT_PASSWORD: "lion"
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - lion
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        user: root
        container_name: MVC-phpmyadmin
        restart: unless-stopped
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "lion"
            MYSQL_ROOT_PASSWORD: "lion"
        networks:
            - lion
volumes:
    mysql_data:
networks:
    lion:
        driver: bridge